const BAD_REQUEST_STATUS = 400;
const SERVER_ERROR_STATUS = 500;
const NOT_FOUND_STATUS = 404;
const SUCCESS_STATUS = 200;
const CREATED_STATUS = 201;
const STATUS_CONFLICT = 409;

module.exports = {
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
  NOT_FOUND_STATUS,
  CREATED_STATUS,
  SUCCESS_STATUS,
  STATUS_CONFLICT,

};

const MONGO_DUPLCATE_ERROR_CODE = 11000;

module.exports = {
  MONGO_DUPLCATE_ERROR_CODE,
};
